### ISSUE TITLE
please help with coding the remaining report subtopics

### ISSUE THREAD

**Issue by dewyia** [dewyia/mms142-groupc-2024#1]
I haven't seen changes to the code since my last update, so I'm assuming no one has edited it. To my fellow web designer members, please help as we only have two days before the deadline. 

Also, we need to put all the subtopics on the website so I can link each article to the navigation bar. Then we can make the footer/references.

**Elements still needed:**
- Subtopic articles 3 to 5
- Images for articles 2 to 5
- Overview of the report (I will insert it tomorrow, dec 7 along with the nav bar)
- References

**Comment by kmbation** [comment]
Hello, I created the code for the sub-topic of AI of the future, however, i am having difficulty where i should put this code as i might disrupt our main code, please let me know where i can paste this thank you so much

**Comment by flyingadobo** [comment]
> I haven't seen changes to the code since my last update, so I'm assuming no one has edited it. To my fellow web designer members, please help as we only have two days before the deadline.
> 
> Also, we need to put all the subtopics on the website so I can link each article to the navigation bar. Then we can make the footer/references.
> 
> **Elements still needed:**
> 
> * Subtopic articles 3 to 5
> * Images for articles 2 to 5
> * Overview of the report (I will insert it tomorrow, dec 7 along with the nav bar)
> * References

Since I wrote article 2, I will look for appropriate images for this.

**Comment by kmbation** [comment]
Hi, I think i will send here the code for the sub-topic of AI for HTML:
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="AI of the Future">
  <title>AI vs Digital Artists: Rifts by Generative AI to the Future of Digital Art Commissions</title>
  <link rel="stylesheet" href="styles.css">
</head>

<body>
  <div class="container">
    <div class="image-container">
      <img src="https://images.unsplash.com/photo-1520052205864-92d242b3a76b?q=80&w=1769&auto=format&fit=crop" alt="AI Now">
      <img src="https://images.unsplash.com/photo-1484557052118-f32bd25b45b5?q=80&w=1769&auto=format&fit=crop" alt="AI Before">
    </div>

    <div class="text-content">
      <h2>AI of the Future</h2>
      <h3>What Can We Expect in the Coming Years?</h3>
      <p>
        Artificial intelligence (AI) has the potential to make far-reaching changes in the digital art landscape in the years to come. As AI algorithms become highly sophisticated, more realistic and high-quality AI art will be created. New AI tools and software will likely emerge, making the AI art creation process faster and more accessible to a greater audience. These tools can also enable personalization, enhancing the human experience and even promoting collaboration between human artists, offering assistance, new ideas, and suggestions, opening up opportunities for innovation. While AI-powered tools can create these new and advanced sets of things in the long run, the long-term impact remains visible in the art industry, specifically for digital artists.
      </p>
      <h3>The Next Evolution of AI-Generated Art</h3>
      <p>So, what's next? Based on ongoing research, the future of AI art is expected to include several improvements, such as (What Is AI-Generated Art?, 2024):
      </p>
      <ul>
        <li>Improved Realism and Detail: With continuous advancements, AI-generated art may feature more detailed and realistic representations.</li>
        <li>Combination of Multiple Media Modalities: Future AI tools may combine text, images, audio, and other media modalities to create multimedia products.</li>
        <li>Enhanced Interactivity and Dynamics: AI-generated art will likely incorporate new dynamic features, improving human interaction and creating immersive experiences.</li>
        <li>Generative Design Across Industries: AI art may expand to various industries, providing creative solutions and applications for design purposes.</li>
        <li>Exploring New Aesthetics: AI art could challenge the traditional or existing notions of art by exploring new and unconventional forms of aesthetics.</li>
      </ul>
      <p>
        Given these possibilities, AI can serve as a powerful tool. Still, it poses risks, particularly for digital art services and commissions. It could threaten the livelihood of digital artists and challenge our notion of art, especially for future generations. Indeed, AI art can be beneficial in its very own way. However, there should be boundaries and limitations, and they should not overshadow the artists' talents, capabilities, and ways of living.
      </p>

      <h3>Navigating Ethical Concerns in the Future of AI Art</h3>
      <p>
        AI-generated art presents various challenges and ethical concerns in the present day. Some current ethical issues surrounding AI art include ownership (intellectual property and rights), privacy, creativity and originality, biased representations, and questions about whether AI could replace a human (Perlman, 2024). These are just a few ethical concerns that need to be addressed. Therefore, regulations and guidelines should be implemented to protect human artists, creators, and their work in the future.
      </p>

      <h3>Art and AI</h3>
      <p>
        The field of art and the role of AI will continue to evolve in the future. Still, there will always be a significant difference between art created by humans and machines. The so-called “human-AI collaboration” may potentially grow in the coming years. But it’s important to remember that art is inherently free, and humans are not bound by standards when creating and expressing themselves through art. Moreover, the ability of artists and creators to add meaning and convey emotion in artwork is something that will remain unique and irreplaceable for humans. Indeed, “while AI may become a part of the creative process, it is the human element that will continue to define art." (AGI Fine Art Expert, 2024).
      </p>
    </div>
  </div>
</body>

</html>

**Comment by kmbation** [comment]
Hi, I will insert here the code for the sub-topic of AI of the Future

HTML:
`<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="AI of the Future">
  <title>AI vs Digital Artists: Rifts by Generative AI to the Future of Digital Art Commissions</title>
  <link rel="stylesheet" href="styles.css">
</head>

<body>
  <div class="container">
    <div class="image-container">
      <img src="https://images.unsplash.com/photo-1520052205864-92d242b3a76b?q=80&w=1769&auto=format&fit=crop" alt="AI Now">
      <img src="https://images.unsplash.com/photo-1484557052118-f32bd25b45b5?q=80&w=1769&auto=format&fit=crop" alt="AI Before">
    </div>

    <div class="text-content">
      <h2>AI of the Future</h2>
      <h3>What Can We Expect in the Coming Years?</h3>
      <p>
        Artificial intelligence (AI) has the potential to make far-reaching changes in the digital art landscape in the years to come. As AI algorithms become highly sophisticated, more realistic and high-quality AI art will be created. New AI tools and software will likely emerge, making the AI art creation process faster and more accessible to a greater audience. These tools can also enable personalization, enhancing the human experience and even promoting collaboration between human artists, offering assistance, new ideas, and suggestions, opening up opportunities for innovation. While AI-powered tools can create these new and advanced sets of things in the long run, the long-term impact remains visible in the art industry, specifically for digital artists.
      </p>
      <h3>The Next Evolution of AI-Generated Art</h3>
      <p>So, what's next? Based on ongoing research, the future of AI art is expected to include several improvements, such as (What Is AI-Generated Art?, 2024):
      </p>
      <ul>
        <li>Improved Realism and Detail: With continuous advancements, AI-generated art may feature more detailed and realistic representations.</li>
        <li>Combination of Multiple Media Modalities: Future AI tools may combine text, images, audio, and other media modalities to create multimedia products.</li>
        <li>Enhanced Interactivity and Dynamics: AI-generated art will likely incorporate new dynamic features, improving human interaction and creating immersive experiences.</li>
        <li>Generative Design Across Industries: AI art may expand to various industries, providing creative solutions and applications for design purposes.</li>
        <li>Exploring New Aesthetics: AI art could challenge the traditional or existing notions of art by exploring new and unconventional forms of aesthetics.</li>
      </ul>
      <p>
        Given these possibilities, AI can serve as a powerful tool. Still, it poses risks, particularly for digital art services and commissions. It could threaten the livelihood of digital artists and challenge our notion of art, especially for future generations. Indeed, AI art can be beneficial in its very own way. However, there should be boundaries and limitations, and they should not overshadow the artists' talents, capabilities, and ways of living.
      </p>

      <h3>Navigating Ethical Concerns in the Future of AI Art</h3>
      <p>
        AI-generated art presents various challenges and ethical concerns in the present day. Some current ethical issues surrounding AI art include ownership (intellectual property and rights), privacy, creativity and originality, biased representations, and questions about whether AI could replace a human (Perlman, 2024). These are just a few ethical concerns that need to be addressed. Therefore, regulations and guidelines should be implemented to protect human artists, creators, and their work in the future.
      </p>

      <h3>Art and AI</h3>
      <p>
        The field of art and the role of AI will continue to evolve in the future. Still, there will always be a significant difference between art created by humans and machines. The so-called “human-AI collaboration” may potentially grow in the coming years. But it’s important to remember that art is inherently free, and humans are not bound by standards when creating and expressing themselves through art. Moreover, the ability of artists and creators to add meaning and convey emotion in artwork is something that will remain unique and irreplaceable for humans. Indeed, “while AI may become a part of the creative process, it is the human element that will continue to define art." (AGI Fine Art Expert, 2024).
      </p>
    </div>
  </div>
</body>

</html>`

**Comment by kmbation** [comment]
Moreover, here is the CSS code for the sub-topic of AI of the Future:


`body {
    font-family: 'Poppins', sans-serif;
    background-color: #FFFAE3; /* Light yellow background */
    margin: 0;
    padding: 0;
    color: #573C27; /* Dark text color */
}

.container {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
    margin: 40px;
}

.text-content {
    flex: 1;
    max-width: 60%;
    margin-right: 20px;
    background-color: #FFFFFF; /* White background for text */
    padding: 30px;
    border-radius: 8px;
}

.text-content h2 {
    font-size: 36px;
    font-weight: 600;
    color: #573C27; /* Dark text color */
    margin-bottom: 10px;
}

.text-content h3 {
    font-size: 24px;
    font-weight: 500;
    color: #573C27; /* Dark text color */
    margin-top: 20px;
}

.text-content p, .text-content ul {
    font-size: 16px;
    line-height: 1.6;
    color: #573C27; /* Dark text color */
}

.text-content ul {
    padding-left: 20px;
}

.image-container {
    flex: 1;
    max-width: 35%;
}

.image-container img {
    width: 100%;
    height: auto;
    margin-bottom: 20px;
    border-radius: 8px;
}

@media screen and (max-width: 768px) {
    .container {
        flex-direction: column;
        align-items: center;
    }

    .text-content {
        max-width: 100%;
        margin-right: 0;
    }

    .image-container {
        max-width: 100%;
    }
}
`

**Comment by kmbation** [comment]
Hello again, i tried to create a zip folder for the codes for both HTML and CSS for the sub-topic AI of the Future for easy transfer of files. let me know if there is anything else i can help with this part. thank you
[Sub-topic AI of the Future.zip](https://github.com/user-attachments/files/18045382/Sub-topic.AI.of.the.Future.zip)

**Comment by dewyia** [comment]
> Hello again, i tried to create a zip folder for the codes for both HTML and CSS for the sub-topic AI of the Future for easy transfer of files. let me know if there is anything else i can help with this part. thank you [Sub-topic AI of the Future.zip](https://github.com/user-attachments/files/18045382/Sub-topic.AI.of.the.Future.zip)

Hi, can you put the code you created in our codespace? Because that's where our current html and css are located. All changes made in the code will be recorded and will reflect in real time so anyone can code directly to our file.

Please also make sure that you change some element titles as I have noticed some div elements in your html have similar container names, and it may cause texts to overlap other elements.

You can copy the settings in my css codes for the articles so it'll be easier. Thank you.


[here's the live preview of our website.](https://improved-computing-machine-r44p9qjr9qrr35xxw-5500.app.github.dev/mms142-group-c.html
)

**Comment by flyingadobo** [comment]
<img width="1436" alt="Sample1 2024-12-07 at 11 49 08 AM" src="https://github.com/user-attachments/assets/9a0a1bb2-891c-42b0-8b0a-1833c3848291">
<img width="1426" alt="Sample2 2024-12-07 at 11 49 41 AM" src="https://github.com/user-attachments/assets/7bdce3d4-4f58-484c-b93f-e9e89e015bfe">
<img width="1357" alt="Sample3 2024-12-07 at 11 50 19 AM" src="https://github.com/user-attachments/assets/ff6e461d-9ae6-40aa-8c2e-1d679cd80c79">
<img width="688" alt="Sample4 2024-12-07 at 11 46 25 AM" src="https://github.com/user-attachments/assets/b2107233-3b78-4b56-b895-1b49a8041148">
<img width="678" alt="Sample5 2024-12-07 at 11 48 04 AM" src="https://github.com/user-attachments/assets/d0a168c3-c28c-4aab-9b77-c9dc65409df8">

Here are the sample images. Photos when photography wasn't considered art. Then sample images created through prompting.

**Comment by wnnxb** [comment]
hello, i can't access the collaboration file for the code
